### ISSUE TITLE
License isn't picked up by crates.io

### ISSUE THREAD

**Issue by daviessm** [gzbakku/letterman#3]
It looks like this crate has a copy of the MIT license but isn't specified as `license="MIT"` in Cargo.toml that's understood by crates.io

**Comment by gzbakku** [comment]
there is a license file and its free to use what do i need to do

**Comment by gzbakku** [comment]
only one license can be described in cargo.toml

**Comment by daviessm** [comment]
Just change `license-file="License.md"` to `license="MIT"` in Cargo.toml

**Comment by gzbakku** [comment]
ok it will be up in a couple of minutes have fun sending emails

**Comment by gzbakku** [comment]
if u need extremely easy email api you can use gzbemail.xyz

**Comment by gzbakku** [comment]
it will be up soon
